<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="hospital_delete.aspx.cs" Inherits="hospital_register.hospital_delete" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1" style="z-index: 1; left: 271px; top: 118px; position: absolute; height: 115px; width: 199px">
            <Columns>
                <asp:BoundField DataField="医院" HeaderText="医院" SortExpression="医院" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT [医院] FROM [表1]"></asp:SqlDataSource>
    </form>
</body>
</html>
